export default [
  {
    checked: true,
    children: [
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102100',
            name: '新增',
            order: 1,
            parentId: '101102',
            perms: 'auth:role:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102101',
            name: '查询',
            order: 2,
            parentId: '101102',
            perms: 'auth:role:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102102',
            name: '修改',
            order: 3,
            parentId: '101102',
            perms: 'auth:role:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102103',
            name: '删除',
            order: 4,
            parentId: '101102',
            perms: 'auth:role:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '100100',
        name: '需求管理',
        order: 1,
        parentId: '100',
        perms: 'cmdb:it:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102100',
            name: '新增',
            order: 1,
            parentId: '101102',
            perms: 'auth:role:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102101',
            name: '查询',
            order: 2,
            parentId: '101102',
            perms: 'auth:role:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102102',
            name: '修改',
            order: 3,
            parentId: '101102',
            perms: 'auth:role:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102103',
            name: '删除',
            order: 4,
            parentId: '101102',
            perms: 'auth:role:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '100100',
        name: '金融产品查询',
        order: 1,
        parentId: '100',
        perms: 'cmdb:it:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102100',
            name: '新增',
            order: 1,
            parentId: '101102',
            perms: 'auth:role:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102101',
            name: '查询',
            order: 2,
            parentId: '101102',
            perms: 'auth:role:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102102',
            name: '修改',
            order: 3,
            parentId: '101102',
            perms: 'auth:role:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102103',
            name: '删除',
            order: 4,
            parentId: '101102',
            perms: 'auth:role:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '100100',
        name: '评价管理',
        order: 1,
        parentId: '100',
        perms: 'cmdb:it:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102100',
            name: '新增',
            order: 1,
            parentId: '101102',
            perms: 'auth:role:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102101',
            name: '查询',
            order: 2,
            parentId: '101102',
            perms: 'auth:role:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102102',
            name: '修改',
            order: 3,
            parentId: '101102',
            perms: 'auth:role:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102103',
            name: '删除',
            order: 4,
            parentId: '101102',
            perms: 'auth:role:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '100100',
        name: '投诉管理',
        order: 1,
        parentId: '100',
        perms: 'cmdb:it:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102100',
            name: '新增',
            order: 1,
            parentId: '101102',
            perms: 'auth:role:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102101',
            name: '查询',
            order: 2,
            parentId: '101102',
            perms: 'auth:role:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102102',
            name: '修改',
            order: 3,
            parentId: '101102',
            perms: 'auth:role:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102103',
            name: '删除',
            order: 4,
            parentId: '101102',
            perms: 'auth:role:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '100100',
        name: '企业中心',
        order: 1,
        parentId: '100',
        perms: 'cmdb:it:view',
        type: 'M',
        url: '#',
      },
    ],
    icon: 'fa fa-gear',
    id: '100',
    name: '企业端',
    order: 1,
    parentId: '0',
    perms: 'cmdb:view',
    type: 'C',
    url: '#',
  },
  {
    checked: true,
    children: [
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102100',
            name: '新增',
            order: 1,
            parentId: '101102',
            perms: 'auth:role:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102101',
            name: '查询',
            order: 2,
            parentId: '101102',
            perms: 'auth:role:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102102',
            name: '修改',
            order: 3,
            parentId: '101102',
            perms: 'auth:role:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102103',
            name: '删除',
            order: 4,
            parentId: '101102',
            perms: 'auth:role:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '100100',
        name: '产品管理',
        order: 1,
        parentId: '100',
        perms: 'cmdb:it:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102100',
            name: '新增',
            order: 1,
            parentId: '101102',
            perms: 'auth:role:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102101',
            name: '查询',
            order: 2,
            parentId: '101102',
            perms: 'auth:role:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102102',
            name: '修改',
            order: 3,
            parentId: '101102',
            perms: 'auth:role:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102103',
            name: '删除',
            order: 4,
            parentId: '101102',
            perms: 'auth:role:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '100100',
        name: '风险管理',
        order: 1,
        parentId: '100',
        perms: 'cmdb:it:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102100',
            name: '新增',
            order: 1,
            parentId: '101102',
            perms: 'auth:role:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102101',
            name: '查询',
            order: 2,
            parentId: '101102',
            perms: 'auth:role:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102102',
            name: '修改',
            order: 3,
            parentId: '101102',
            perms: 'auth:role:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102103',
            name: '删除',
            order: 4,
            parentId: '101102',
            perms: 'auth:role:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '100100',
        name: '需求管理',
        order: 1,
        parentId: '100',
        perms: 'cmdb:it:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102100',
            name: '新增',
            order: 1,
            parentId: '101102',
            perms: 'auth:role:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102101',
            name: '查询',
            order: 2,
            parentId: '101102',
            perms: 'auth:role:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102102',
            name: '修改',
            order: 3,
            parentId: '101102',
            perms: 'auth:role:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102103',
            name: '删除',
            order: 4,
            parentId: '101102',
            perms: 'auth:role:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '100100',
        name: '投诉管理',
        order: 1,
        parentId: '100',
        perms: 'cmdb:it:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102100',
            name: '新增',
            order: 1,
            parentId: '101102',
            perms: 'auth:role:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102101',
            name: '查询',
            order: 2,
            parentId: '101102',
            perms: 'auth:role:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102102',
            name: '修改',
            order: 3,
            parentId: '101102',
            perms: 'auth:role:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102103',
            name: '删除',
            order: 4,
            parentId: '101102',
            perms: 'auth:role:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '100100',
        name: '机构中心',
        order: 1,
        parentId: '100',
        perms: 'cmdb:it:view',
        type: 'M',
        url: '#',
      },
    ],
    icon: 'fa fa-gear',
    id: '100',
    name: '金融机构',
    order: 1,
    parentId: '0',
    perms: 'cmdb:view',
    type: 'C',
    url: '#',
  },
  {
    checked: true,
    children: [
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100100',
            name: '新增',
            order: 1,
            parentId: '101100',
            perms: 'auth:user:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100101',
            name: '查询',
            order: 2,
            parentId: '101100',
            perms: 'auth:user:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100102',
            name: '修改',
            order: 3,
            parentId: '101100',
            perms: 'auth:user:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100103',
            name: '删除',
            order: 4,
            parentId: '101100',
            perms: 'auth:user:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '101100',
        name: '企业管理',
        order: 1,
        parentId: '101',
        perms: 'auth:user:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100100',
            name: '新增',
            order: 1,
            parentId: '101100',
            perms: 'auth:user:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100101',
            name: '查询',
            order: 2,
            parentId: '101100',
            perms: 'auth:user:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100102',
            name: '修改',
            order: 3,
            parentId: '101100',
            perms: 'auth:user:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100103',
            name: '删除',
            order: 4,
            parentId: '101100',
            perms: 'auth:user:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '101100',
        name: '金融机构管理',
        order: 1,
        parentId: '101',
        perms: 'auth:user:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100100',
            name: '新增',
            order: 1,
            parentId: '101100',
            perms: 'auth:user:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100101',
            name: '查询',
            order: 2,
            parentId: '101100',
            perms: 'auth:user:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100102',
            name: '修改',
            order: 3,
            parentId: '101100',
            perms: 'auth:user:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100103',
            name: '删除',
            order: 4,
            parentId: '101100',
            perms: 'auth:user:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '101100',
        name: '交易管理',
        order: 1,
        parentId: '101',
        perms: 'auth:user:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100100',
            name: '新增',
            order: 1,
            parentId: '101100',
            perms: 'auth:user:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100101',
            name: '查询',
            order: 2,
            parentId: '101100',
            perms: 'auth:user:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100102',
            name: '修改',
            order: 3,
            parentId: '101100',
            perms: 'auth:user:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100103',
            name: '删除',
            order: 4,
            parentId: '101100',
            perms: 'auth:user:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '101100',
        name: '投诉管理',
        order: 1,
        parentId: '101',
        perms: 'auth:user:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100100',
            name: '新增',
            order: 1,
            parentId: '101100',
            perms: 'auth:user:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100101',
            name: '查询',
            order: 2,
            parentId: '101100',
            perms: 'auth:user:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100102',
            name: '修改',
            order: 3,
            parentId: '101100',
            perms: 'auth:user:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100103',
            name: '删除',
            order: 4,
            parentId: '101100',
            perms: 'auth:user:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '101100',
        name: '日志管理',
        order: 1,
        parentId: '101',
        perms: 'auth:user:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100100',
            name: '新增',
            order: 1,
            parentId: '101100',
            perms: 'auth:user:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100101',
            name: '查询',
            order: 2,
            parentId: '101100',
            perms: 'auth:user:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100102',
            name: '修改',
            order: 3,
            parentId: '101100',
            perms: 'auth:user:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100103',
            name: '删除',
            order: 4,
            parentId: '101100',
            perms: 'auth:user:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '101100',
        name: '主页管理',
        order: 1,
        parentId: '101',
        perms: 'auth:user:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100100',
            name: '新增',
            order: 1,
            parentId: '101100',
            perms: 'auth:user:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100101',
            name: '查询',
            order: 2,
            parentId: '101100',
            perms: 'auth:user:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100102',
            name: '修改',
            order: 3,
            parentId: '101100',
            perms: 'auth:user:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101100103',
            name: '删除',
            order: 4,
            parentId: '101100',
            perms: 'auth:user:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '101100',
        name: '用户管理',
        order: 1,
        parentId: '101',
        perms: 'auth:user:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102100',
            name: '新增',
            order: 1,
            parentId: '101102',
            perms: 'auth:role:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102101',
            name: '查询',
            order: 2,
            parentId: '101102',
            perms: 'auth:role:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102102',
            name: '修改',
            order: 3,
            parentId: '101102',
            perms: 'auth:role:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101102103',
            name: '删除',
            order: 4,
            parentId: '101102',
            perms: 'auth:role:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '101102',
        name: '角色管理',
        order: 2,
        parentId: '101',
        perms: 'auth:role:view',
        type: 'M',
        url: '#',
      },
      {
        checked: true,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101103100',
            name: '新增',
            order: 1,
            parentId: '101103',
            perms: 'auth:dept:add',
            type: 'F',
            url: '#',
          },
          {
            checked: true,
            children: [],
            icon: 'fa fa-gear',
            id: '101103101',
            name: '查询',
            order: 2,
            parentId: '101103',
            perms: 'auth:dept:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101103102',
            name: '修改',
            order: 3,
            parentId: '101103',
            perms: 'auth:dept:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101103103',
            name: '删除',
            order: 4,
            parentId: '101103',
            perms: 'auth:dept:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '101103',
        name: '部门管理',
        order: 2,
        parentId: '101',
        perms: 'auth:dept:view',
        type: 'M',
        url: '#',
      },
      {
        checked: false,
        children: [
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101104100',
            name: '新增',
            order: 1,
            parentId: '101104',
            perms: 'auth:menu:add',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101104101',
            name: '查询',
            order: 2,
            parentId: '101104',
            perms: 'auth:menu:search',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101104102',
            name: '修改',
            order: 3,
            parentId: '101104',
            perms: 'auth:menu:edit',
            type: 'F',
            url: '#',
          },
          {
            checked: false,
            children: [],
            icon: 'fa fa-gear',
            id: '101104103',
            name: '删除',
            order: 4,
            parentId: '101104',
            perms: 'auth:menu:remove',
            type: 'F',
            url: '#',
          },
        ],
        icon: 'fa fa-gear',
        id: '101104',
        name: '权限管理',
        order: 2,
        parentId: '101',
        perms: 'auth:menu:view',
        type: 'M',
        url: '#',
      },
    ],
    icon: 'fa fa-gear',
    id: '101',
    name: '政府部门',
    order: 2,
    parentId: '0',
    perms: 'auth:view',
    type: 'C',
    url: '#',
  },
];
